### ISSUE TITLE
SortTupleArray<T1, T2, T3> issue

### ISSUE THREAD

**Issue by aorgish** [trewor92/02-Generics#3]
1) Вот такой стиль называется copy-paste-стиль. Его лучше избегать:
https://github.com/trewor92/02-Generics/blob/ee5627eb26dba5f9fd8de9436ae01f61d9000f2b/GenericApplication/Generics.cs#L154-L163

Для исправления находиться изменяемая часть и выноситься в переменную, а одинаковая часть записывается один раз с учетом такой переменной (переменных). В данном случае изменяемая часть - это x=>x.Item1, x=>x.Item2 и x=>x.Item3

2) Массив копируется в памяти, это лишние затраты по производительности и памяти:
https://github.com/trewor92/02-Generics/blob/ee5627eb26dba5f9fd8de9436ae01f61d9000f2b/GenericApplication/Generics.cs#L175-L179
Для исправления надо использовать методы, которые сортируют массив напрямую: https://docs.microsoft.com/en-us/dotnet/api/system.array.sort?view=netframework-4.7.2

**Comment by trewor92** [comment]
https://github.com/trewor92/02-Generics/blob/ae4aaa18b7eff1ebf866b2c1b713eab72525d960/GenericApplication/Generics.cs#L142-L167

 Copy-paste-стиль в данном случае позволяет значительно сократить код, поскольку второй аргумент в методе Array.Sort это однострочный массив, который выделить из типа Tuple, сложнее чем трудозатратнее лямбда выражение, а Func<> в качестве второго аргумента метод Array.Sort не принимает. Подскажите как поступать в такой ситуации?

**Comment by aorgish** [comment]
Для начала нужно избавиться от проверок ascending. Для этого можно заметить, что кроме замены x и у местами, есть вариант поменять знак у результата CompareTo.
```
var koeff = ascending? +1 : -1;
```
Дальше у нас меняется только Item1, Item2, Item3, их всех объединяет только то, что они IComparable. Значит нам нужен метод, который для объекта по номеру вернет нужное поле типа IComparable
```
Func<Tuple<T1, T2, T3, IComparable>[] funcs = new [] {  x=> x.Item1, x=>x.Item2, x=>x.Item3 };
var getProp = funcs[sortedColumn]; // Это удобно еще и тем, что сразу выкидывает IndexOfRangeException, нам не надо об этом заботиться 
```
Дальше все зависимости у нас уже в переменных, осталось просто один раз использовать общий код
```
Array.Sort(array, (x,y) => koeff * getProp(x).CompareTo(getProp(y)));
```
Минус этого варианта - это то, что используется IComparable.CompareTo, который делает boxing (приводит к типу Object) значимые типы (value types). А операция boxing/unboxing достаточно затратная. Поэтому осталось сделать так, чтобы использовались IComparable<T> вместо IComparable, в этом случае производительность будет лучше (это самостоятельное задание).
И этот простейший прием inversion of control надо запомнить, его надо применять вместо любого copy-paste.
(Код писался прямо в браузере, так что где-то могут быть описки и не компилироваться, но идея должна быть понятна)

**Comment by trewor92** [comment]
Есть вопрос! Прием inversion of control - в данном случае означает что мы переходим от конкретного типа Т к абстрактному интерфейсу IComparablе, тем самым убираем возможную зависимость Array.Sort от конкретного типа T и создаем две зависимости типа T от интерфейса IComparable(тип T реализует интерфейс) и Array.Sort от IComparable (аргумент)? 


В моем 3 коммите, поскольку требуется применение IComparable<T>, я не имел права переходить к IComparable (общего для T1,T2,T3), и был вынужден возвратить int  x.Compare(y), но зато использую не IComparable.CompareTo, а IComparable<T>.CompareTo. Т.е. тут без IoC.
https://github.com/trewor92/02-Generics/blob/45773edc93e3267b1f01c52ad792529d4498f1a9/GenericApplication/Generics.cs#L143-L145

**Comment by aorgish** [comment]
Почти так. Тoлько в данном случае IoC работает на уровне кода внутри метода, а не на уровне зависимостей классов. В самом первом варианте был copy-paste стиль, и при изменении требований опять же требовалось скопировать большой кусок кода или исправлять в 10 местах. Вытянув все засисимые куски в переменные, мы инвертировали зависимости на уровне обычного кода, теперь при изменении условий код меняется только в одном месте.
Последний вариант все же имеет внутри массива comparers похожие куски кода, но тут надо находить компромисс между скоростью работы и copy-paste стилем. 

И в объявлении массива можно сократить тип для массива, компилятор сам его должен вывести:
```
Func < Tuple<T1, T2, T3>,Tuple<T1, T2, T3>, int>[] comparers =  new [] { ... };
```
