### ISSUE TITLE
TimeoutSafeInvoke<T> issue

### ISSUE THREAD

**Issue by aorgish** [trewor92/02-Generics#5]
Не совсем понятно, зачем эта строка:
https://github.com/trewor92/02-Generics/blob/ee5627eb26dba5f9fd8de9436ae01f61d9000f2b/GenericApplication/Generics.cs#L230
И сам подход сохранения exception в переменную выглядит непривычно. Никто так не пишет. Обычно исключение выкидывается сразу в блоке catch, если его перехватили и решили не обрабатывать.

**Comment by trewor92** [comment]
https://github.com/trewor92/02-Generics/blob/ae4aaa18b7eff1ebf866b2c1b713eab72525d960/GenericApplication/Generics.cs#L215-L239

Чем заглушить функцию , поскольку компилятор считает что do-while может не вернуть значение типа T и подчеркивает функцию, пока его не заглушил исключение или return 236

**Comment by aorgish** [comment]
Обычно do-while никто не использует, его очень тяжело понимать. Вместо этого применяют `while(true) { ... }` с выходом из цикла в нужном месте (по условию или без). 

И тут переменная maxAttemptCount используется только в одном месте, в строке 230 почему-то идет сравнение с литералом.
